name: 1 - Setup

on:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Upload node_modules artifact
        uses: actions/upload-artifact@v7
        with:
          name: node-modules
          path: node_modules
          retention-days: 1
