name: 2 - Build

on:
  workflow_run:
    workflows: ["1 - Setup"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Download node_modules artifact
        uses: actions/download-artifact@v7
        with:
          name: node-modules
          path: node_modules
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Build
        run: pnpm build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
          retention-days: 1
